version: '3'
services:
  web:
    build: # add custom dockerfile (opposed to build: .)
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: # map current dir to the containers
      - /usr/app/node_modules
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: # map current dir to the containers
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]